### ISSUE TITLE
Failed at the msgpack@0.2.4 install script

### ISSUE THREAD

**Issue by LittleMonsterAK** [msgpack/msgpack-node#19]
when i install msgpack with node 0.11.12,there is so many errors occured ,just like below:
> hashring@3.0.0 install /Users/wangjianhua/project/upyun/nodejs/Alvida/node_modules/memcached/node_modules/hashring
> node-gyp rebuild

  CXX(target) Release/obj.target/hashvalue/src/hashvalue.o
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:189:74: error: too many arguments to function call, expected at most 3, have 4
    return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
           ~~~~~~~~~~~~~~~~~~                                            ^~~~
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:3585:3: note: 'New' declared here
  static Local<Signature> New(Handle<FunctionTemplate> receiver =
  ^
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:217:27: error: cannot initialize a parameter of type 'int' with an rvalue of type 'v8::Isolate *'
    return v8::Array::New(v8::Isolate::GetCurrent());
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:2335:31: note: passing argument to parameter 'length' here
  static Local<Array> New(int length = 0);
                              ^
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:222:54: error: too many arguments to function call, expected at most single argument 'length', have 2 arguments
    return v8::Array::New(v8::Isolate::GetCurrent(), length);
           ~~~~~~~~~~~~~~                            ^~~~~~
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:2335:3: note: 'New' declared here
  static Local<Array> New(int length = 0);
  ^
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:227:53: error: too many arguments to function call, expected single argument 'time', have 2 arguments
    return v8::Date::New(v8::Isolate::GetCurrent(), time).As<v8::Date>();
           ~~~~~~~~~~~~~                            ^~~~
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:2866:3: note: 'New' declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:227:70: error: expected '(' for function-style cast or type construction
    return v8::Date::New(v8::Isolate::GetCurrent(), time).As<v8::Date>();
                                                             ~~~~~~~~^
../node_modules/nan/nan.h:227:72: error: expected expression
    return v8::Date::New(v8::Isolate::GetCurrent(), time).As<v8::Date>();
                                                                       ^
../node_modules/nan/nan.h:232:53: error: too many arguments to function call, expected single argument 'time', have 2 arguments
    return v8::Date::New(v8::Isolate::GetCurrent(), time).As<v8::Date>();
           ~~~~~~~~~~~~~                            ^~~~
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:2866:3: note: 'New' declared here
  static Local<Value> New(double time);
  ^
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:232:70: error: expected '(' for function-style cast or type construction
    return v8::Date::New(v8::Isolate::GetCurrent(), time).As<v8::Date>();
                                                             ~~~~~~~~^
../node_modules/nan/nan.h:232:72: error: expected expression
    return v8::Date::New(v8::Isolate::GetCurrent(), time).As<v8::Date>();
                                                                       ^
../node_modules/nan/nan.h:235:15: error: no type named 'UnboundScript' in namespace 'v8'
  typedef v8::UnboundScript NanUnboundScript;
          ~~~~^
../node_modules/nan/nan.h:243:9: error: no member named 'ScriptCompiler' in namespace 'v8'
    v8::ScriptCompiler::Source source(s, origin);
    ~~~~^
../node_modules/nan/nan.h:244:16: error: no member named 'ScriptCompiler' in namespace 'v8'
    return v8::ScriptCompiler::CompileUnbound(
           ~~~~^
../node_modules/nan/nan.h:245:37: error: use of undeclared identifier 'source'; did you mean 'v8::Extension::source'?
        v8::Isolate::GetCurrent(), &source);
                                    ^~~~~~
                                    v8::Extension::source
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:3712:46: note: 'v8::Extension::source' declared here
  const String::ExternalAsciiStringResource* source() const {
                                             ^
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:245:36: error: must explicitly qualify name of member function when taking its address
        v8::Isolate::GetCurrent(), &source);
                                   ^~~~~~~
                                    Extension::
../node_modules/nan/nan.h:252:9: error: no member named 'ScriptCompiler' in namespace 'v8'
    v8::ScriptCompiler::Source source(s);
    ~~~~^
../node_modules/nan/nan.h:253:16: error: no member named 'ScriptCompiler' in namespace 'v8'
    return v8::ScriptCompiler::CompileUnbound(
           ~~~~^
../node_modules/nan/nan.h:254:37: error: use of undeclared identifier 'source'; did you mean 'v8::Extension::source'?
        v8::Isolate::GetCurrent(), &source);
                                    ^~~~~~
                                    v8::Extension::source
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:3712:46: note: 'v8::Extension::source' declared here
  const String::ExternalAsciiStringResource* source() const {
                                             ^
In file included from ../src/hashvalue.cc:1:
../node_modules/nan/nan.h:254:36: error: must explicitly qualify name of member function when taking its address
        v8::Isolate::GetCurrent(), &source);
                                   ^~~~~~~
                                    Extension::
../node_modules/nan/nan.h:279:36: error: too many arguments to function call, expected single argument 'value', have 2 arguments
        v8::Isolate::GetCurrent(), val).As<v8::NumberObject>();
                                   ^~~
/Users/wangjianhua/.node-gyp/0.11.12/deps/v8/include/v8.h:2904:3: note: 'New' declared here
  static Local<Value> New(double value);
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/hashvalue/src/hashvalue.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/nvm/0.7.0/v0.11.12/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1045:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/Cellar/nvm/0.7.0/v0.11.12/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wangjianhua/project/upyun/nodejs/Alvida/node_modules/memcached/node_modules/hashring
gyp ERR! node -v v0.11.12
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! msgpack@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msgpack@0.2.4 install script.
npm ERR! This is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "/usr/local/opt/nvm/v0.11.12/bin/node" "/usr/local/opt/nvm/v0.11.12/bin/npm" "install"
npm ERR! cwd /Users/wangjianhua/project/upyun/nodejs/Alvida
npm ERR! node -v v0.11.12
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 


anyone can help me ? thx!

**Comment by sdepold** [comment]
Same happens for iojs @ 1.0.2:

```
In file included from ../src/msgpack.cc:9:0:
../node_modules/nan/nan.h:409:19: error: 'NanNew' declared as an 'inline' variable
../node_modules/nan/nan.h:409:19: warning: 'always_inline' attribute ignored [-Wattributes]
../node_modules/nan/nan.h:409:19: error: 'v8::Local<v8::String> NanNew' redeclared as different kind of symbol
../node_modules/nan/nan.h:403:36: error: previous declaration of 'v8::Local<v8::String> NanNew(v8::String::ExternalStringResource*)'
../node_modules/nan/nan.h:409:7: error: 'ExternalAsciiStringResource' is not a member of 'v8::String'
../node_modules/nan/nan.h:409:48: error: 'resource' was not declared in this scope
../node_modules/nan/nan.h: In function 'bool _NanGetExternalParts(v8::Handle<v8::Value>, const char**, size_t*)':
../node_modules/nan/nan.h:1728:12: error: 'class v8::String' has no member named 'IsExternalAscii'
../node_modules/nan/nan.h:1729:11: error: 'ExternalAsciiStringResource' in 'class v8::String' does not name a type
../node_modules/nan/nan.h:1730:5: error: 'ext' was not declared in this scope
../node_modules/nan/nan.h:1730:16: error: 'class v8::String' has no member named 'GetExternalAsciiStringResource'
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
```

**Comment by godsflaw** [comment]
I think this is resolved.
