### ISSUE TITLE
Failed to build with Node V4.2.2

### ISSUE THREAD

**Issue by ssuarezbe** [msgpack/msgpack-node#31]
Hi. I just had a running application that use msgpack on a Node V0.12.x.

But now that I have updated my Node to V4.2.2 it can not build the msgpack

I tried msgpack@1.0.0,  msgpack@1.0.1 and msgpack@1.0.2 and none of them work. 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-68-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! project/node_modules/msgpack
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "msgpack@1.0.0"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! msgpack@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msgpack@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    /npm-debug.log

```

Any help will be really appreciated.

**Comment by ssuarezbe** [comment]
Sorry, it now work on node 0.12.8. I just need to upgrade my g++ and gcc compiler from 4.6.x to 4.7.x or above.

I suppose that it also runs on node >= 4.x.

**Comment by alexjstubbs** [comment]
```bash 

$ g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ npm install msgpack
\
> msgpack@1.0.2 install /opt/code/node_modules/msgpack
> node-gyp rebuild

make: Entering directory `/opt/code/node_modules/msgpack/build'
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
/tmp/ccgJepQE.s: Assembler messages:
/tmp/ccgJepQE.s:3214: Error: expecting string instruction after `rep'
make: *** [Release/obj.target/msgpackBinding/src/msgpack.o] Error 1
make: Leaving directory `/opt/code/node_modules/msgpack/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/octane5/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "/home/octane5/.nvm/versions/node/v4.2.2/bin/node" "/home/octane5/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/code/node_modules/msgpack
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 2.6.32-573.3.1.el6.x86_64
npm ERR! argv "/home/octane5/.nvm/versions/node/v4.2.2/bin/node" "/home/octane5/.nvm/versions/node/v4.2.2/bin/npm" "install" "msgpack"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! msgpack@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msgpack@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/code/npm-debug.log` 

```

**Comment by mastash3ff** [comment]
Also fails on node v5

**Comment by ssuarezbe** [comment]
System:
-  OS: Ubuntu 12.04 64_x
- g++: version 4.7.3 (Ubuntu/Linaro 4.7.3-2ubuntu1~12.04) 
- gcc: version 4.7.3 (Ubuntu/Linaro 4.7.3-2ubuntu1~12.04)

On Node:
* 5.2.4 (prebuilt) -> Works
* 4.2.4 (prebuilt) -> Works

Please check If the error still happens.

**Comment by enochgroot** [comment]
Fixed in 2.0.0 (#25687, e04c9b55). Node 4 is outside `engines.node: ">=18"`.

**Comment by enochgroot** [comment]
Re-evaluated on master `e04c9b55`. `engines.node` is `>=18`; CI is Node 18/20/22. Node 4 is unsupported. Closing as obsolete.
