### ISSUE TITLE
Doesnt work on 4.2.6

### ISSUE THREAD

**Issue by Petterholm** [msgpack/msgpack-node#33]
IT doesnt work on 4.2.6 i have also tried 0.10 and 0.12

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'msgpack' ]
2 info using npm@2.14.12
3 info using node@v4.2.6
4 verbose config Skipping project config: C:\Users\Petter/.npmrc. (matches userconfig)
5 verbose install initial load of C:\Users\Petter\package.json
6 verbose installManyTop reading scoped package data from C:\Users\Petter\node_modules\nan\package.json
7 verbose readDependencies loading dependencies from C:\Users\Petter\package.json
8 silly cache add args [ 'msgpack', null ]
9 verbose cache add spec msgpack
10 silly cache add parsed spec Result {
10 silly cache add   raw: 'msgpack',
10 silly cache add   scope: null,
10 silly cache add   name: 'msgpack',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: 'latest',
10 silly cache add   type: 'tag' }
11 silly addNamed msgpack@latest
12 verbose addNamed "latest" is being treated as a dist-tag for msgpack
13 info addNameTag [ 'msgpack', 'latest' ]
14 silly mapToRegistry name msgpack
15 silly mapToRegistry using default registry
16 silly mapToRegistry registry https://registry.npmjs.org/
17 silly mapToRegistry uri https://registry.npmjs.org/msgpack
18 verbose addNameTag registry:https://registry.npmjs.org/msgpack not in flight; fetching
19 verbose request uri https://registry.npmjs.org/msgpack
20 verbose request no auth needed
21 info attempt registry request try #1 at 15:01:52
22 verbose request id 8e3c3758b9400929
23 verbose etag "3HVEMFQYGOP6Q21FECOBT6SOM"
24 http request GET https://registry.npmjs.org/msgpack
25 http 304 https://registry.npmjs.org/msgpack
26 verbose headers { date: 'Sun, 24 Jan 2016 14:01:46 GMT',
26 verbose headers   via: '1.1 varnish',
26 verbose headers   'cache-control': 'max-age=300',
26 verbose headers   etag: '"3HVEMFQYGOP6Q21FECOBT6SOM"',
26 verbose headers   age: '0',
26 verbose headers   connection: 'keep-alive',
26 verbose headers   'x-served-by': 'cache-ams4131-AMS',
26 verbose headers   'x-cache': 'HIT',
26 verbose headers   'x-cache-hits': '1',
26 verbose headers   'x-timer': 'S1453644106.123112,VS0,VE664',
26 verbose headers   vary: 'Accept' }
27 silly get cb [ 304,
27 silly get   { date: 'Sun, 24 Jan 2016 14:01:46 GMT',
27 silly get     via: '1.1 varnish',
27 silly get     'cache-control': 'max-age=300',
27 silly get     etag: '"3HVEMFQYGOP6Q21FECOBT6SOM"',
27 silly get     age: '0',
27 silly get     connection: 'keep-alive',
27 silly get     'x-served-by': 'cache-ams4131-AMS',
27 silly get     'x-cache': 'HIT',
27 silly get     'x-cache-hits': '1',
27 silly get     'x-timer': 'S1453644106.123112,VS0,VE664',
27 silly get     vary: 'Accept' } ]
28 verbose etag https://registry.npmjs.org/msgpack from cache
29 verbose get saving msgpack to C:\Users\Petter\AppData\Roaming\npm-cache\registry.npmjs.org\msgpack.cache.json
30 silly addNameTag next cb for msgpack with tag latest
31 silly addNamed msgpack@1.0.2
32 verbose addNamed "1.0.2" is a plain semver version for msgpack
33 silly cache afterAdd msgpack@1.0.2
34 verbose afterAdd C:\Users\Petter\AppData\Roaming\npm-cache\msgpack\1.0.2\package\package.json not in flight; writing
35 verbose afterAdd C:\Users\Petter\AppData\Roaming\npm-cache\msgpack\1.0.2\package\package.json written
36 silly install resolved [ { name: 'msgpack',
36 silly install resolved     description: 'A space-efficient object serialization library for node.js',
36 silly install resolved     version: '1.0.2',
36 silly install resolved     homepage: 'https://github.com/msgpack/msgpack-node',
36 silly install resolved     contributors:
36 silly install resolved      [ [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object],
36 silly install resolved        [Object] ],
36 silly install resolved     repository:
36 silly install resolved      { type: 'git',
36 silly install resolved        url: 'git+https://github.com/msgpack/msgpack-node.git' },
36 silly install resolved     main: './lib/msgpack',
36 silly install resolved     directories: { lib: 'lib' },
36 silly install resolved     dependencies: { nan: '^2.0.9' },
36 silly install resolved     devDependencies: { nodeunit: 'https://github.com/godsflaw/nodeunit/archive/master.tar.gz' },
36 silly install resolved     engines: { node: '>=0.12.7' },
36 silly install resolved     bin:
36 silly install resolved      { json2msgpack: './bin/json2msgpack',
36 silly install resolved        msgpack2json: './bin/msgpack2json' },
36 silly install resolved     scripts: { test: './run_tests', install: 'node-gyp rebuild' },
36 silly install resolved     gypfile: true,
36 silly install resolved     gitHead: '3c05e7fc10a2b9e8d4843f1c7e441656e9b2561d',
36 silly install resolved     bugs: { url: 'https://github.com/msgpack/msgpack-node/issues' },
36 silly install resolved     _id: 'msgpack@1.0.2',
36 silly install resolved     _shasum: '923e2c5cffa65c8418e9b228d1124793969c429c',
36 silly install resolved     _from: 'msgpack@latest',
36 silly install resolved     _npmVersion: '2.14.2',
36 silly install resolved     _nodeVersion: '4.0.0',
36 silly install resolved     _npmUser: { name: 'godsflaw', email: 'chris@dod.net' },
36 silly install resolved     maintainers: [ [Object], [Object], [Object] ],
36 silly install resolved     dist:
36 silly install resolved      { shasum: '923e2c5cffa65c8418e9b228d1124793969c429c',
36 silly install resolved        tarball: 'http://registry.npmjs.org/msgpack/-/msgpack-1.0.2.tgz' },
36 silly install resolved     _resolved: 'https://registry.npmjs.org/msgpack/-/msgpack-1.0.2.tgz',
36 silly install resolved     readme: 'ERROR: No README data found!' } ]
37 info install msgpack@1.0.2 into C:\Users\Petter
38 info installOne msgpack@1.0.2
39 verbose installOne of msgpack to C:\Users\Petter not in flight; installing
40 verbose lock using C:\Users\Petter\AppData\Roaming\npm-cache_locks\msgpack-68ee4676dba95d81.lock for C:\Users\Petter\node_modules\msgpack
41 silly install write writing msgpack 1.0.2 to C:\Users\Petter\node_modules\msgpack
42 verbose unbuild node_modules\msgpack
43 silly gentlyRm C:\Users\Petter\node_modules\msgpack is being purged from base C:\Users\Petter
44 verbose gentlyRm don't care about contents; nuking C:\Users\Petter\node_modules\msgpack
45 verbose tar unpack C:\Users\Petter\AppData\Roaming\npm-cache\msgpack\1.0.2\package.tgz
46 verbose tar unpacking to C:\Users\Petter\node_modules\msgpack
47 silly gentlyRm C:\Users\Petter\node_modules\msgpack is being purged
48 verbose gentlyRm don't care about contents; nuking C:\Users\Petter\node_modules\msgpack
49 silly gunzTarPerm modes [ '777', '666' ]
50 silly gunzTarPerm extractEntry package.json
51 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
52 silly gunzTarPerm extractEntry .npmignore
53 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
54 silly gunzTarPerm extractEntry README.md
55 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
56 silly gunzTarPerm extractEntry LICENSE
57 silly gunzTarPerm modified mode [ 'LICENSE', 420, 438 ]
58 silly gunzTarPerm extractEntry bin/json2msgpack
59 silly gunzTarPerm modified mode [ 'bin/json2msgpack', 493, 511 ]
60 silly gunzTarPerm extractEntry bin/msgpack2json
61 silly gunzTarPerm modified mode [ 'bin/msgpack2json', 493, 511 ]
62 silly gunzTarPerm extractEntry binding.gyp
63 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
64 silly gunzTarPerm extractEntry deps/msgpack/LICENSE
65 silly gunzTarPerm modified mode [ 'deps/msgpack/LICENSE', 420, 438 ]
66 silly gunzTarPerm extractEntry deps/msgpack/msgpack.h
67 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack.h', 420, 438 ]
68 silly gunzTarPerm extractEntry deps/msgpack/AUTHORS
69 silly gunzTarPerm modified mode [ 'deps/msgpack/AUTHORS', 420, 438 ]
70 silly gunzTarPerm extractEntry deps/msgpack/gcc_atomic.hpp
71 silly gunzTarPerm modified mode [ 'deps/msgpack/gcc_atomic.hpp', 420, 438 ]
72 silly gunzTarPerm extractEntry deps/msgpack/msgpack/sysdep.h
73 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/sysdep.h', 420, 438 ]
74 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/list.hpp
75 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/list.hpp', 420, 438 ]
76 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/adaptor_base.hpp
77 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/adaptor_base.hpp', 420, 438 ]
78 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/char_ptr.hpp
79 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/char_ptr.hpp', 420, 438 ]
80 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/check_container_size.hpp
81 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/check_container_size.hpp',
81 silly gunzTarPerm   420,
81 silly gunzTarPerm   438 ]
82 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/cpp11/array.hpp
83 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/cpp11/array.hpp', 420, 438 ]
84 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/cpp11/array_char.hpp
85 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/cpp11/array_char.hpp', 420, 438 ]
86 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/cpp11/forward_list.hpp
87 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/cpp11/forward_list.hpp',
87 silly gunzTarPerm   420,
87 silly gunzTarPerm   438 ]
88 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/cpp11/tuple.hpp
89 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/cpp11/tuple.hpp', 420, 438 ]
90 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/cpp11/unordered_map.hpp
91 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/cpp11/unordered_map.hpp',
91 silly gunzTarPerm   420,
91 silly gunzTarPerm   438 ]
92 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/cpp11/unordered_set.hpp
93 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/cpp11/unordered_set.hpp',
93 silly gunzTarPerm   420,
93 silly gunzTarPerm   438 ]
94 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/define.hpp
95 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/define.hpp', 420, 438 ]
96 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/deque.hpp
97 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/deque.hpp', 420, 438 ]
98 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/detail/cpp03_define.hpp
99 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/detail/cpp03_define.hpp',
99 silly gunzTarPerm   420,
99 silly gunzTarPerm   438 ]
100 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/detail/cpp03_msgpack_tuple.hpp
101 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/detail/cpp03_msgpack_tuple.hpp',
101 silly gunzTarPerm   420,
101 silly gunzTarPerm   438 ]
102 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/detail/cpp11_define.hpp
103 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/detail/cpp11_define.hpp',
103 silly gunzTarPerm   420,
103 silly gunzTarPerm   438 ]
104 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp
105 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp',
105 silly gunzTarPerm   420,
105 silly gunzTarPerm   438 ]
106 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/fixint.hpp
107 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/fixint.hpp', 420, 438 ]
108 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/float.hpp
109 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/float.hpp', 420, 438 ]
110 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/int.hpp
111 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/int.hpp', 420, 438 ]
112 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/bool.hpp
113 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/bool.hpp', 420, 438 ]
114 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/map.hpp
115 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/map.hpp', 420, 438 ]
116 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/msgpack_tuple.hpp
117 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/msgpack_tuple.hpp', 420, 438 ]
118 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/nil.hpp
119 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/nil.hpp', 420, 438 ]
120 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/pair.hpp
121 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/pair.hpp', 420, 438 ]
122 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/raw.hpp
123 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/raw.hpp', 420, 438 ]
124 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/set.hpp
125 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/set.hpp', 420, 438 ]
126 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/string.hpp
127 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/string.hpp', 420, 438 ]
128 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/tr1/unordered_map.hpp
129 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/tr1/unordered_map.hpp',
129 silly gunzTarPerm   420,
129 silly gunzTarPerm   438 ]
130 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/tr1/unordered_set.hpp
131 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/tr1/unordered_set.hpp',
131 silly gunzTarPerm   420,
131 silly gunzTarPerm   438 ]
132 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/vector.hpp
133 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/vector.hpp', 420, 438 ]
134 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/vector_bool.hpp
135 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/vector_bool.hpp', 420, 438 ]
136 silly gunzTarPerm extractEntry deps/msgpack/msgpack/adaptor/vector_char.hpp
137 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/adaptor/vector_char.hpp', 420, 438 ]
138 silly gunzTarPerm extractEntry deps/msgpack/msgpack/detail/cpp03_zone.hpp
139 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/detail/cpp03_zone.hpp', 420, 438 ]
140 silly gunzTarPerm extractEntry deps/msgpack/msgpack/detail/cpp11_zone.hpp
141 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/detail/cpp11_zone.hpp', 420, 438 ]
142 silly gunzTarPerm extractEntry deps/msgpack/msgpack/fbuffer.h
143 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/fbuffer.h', 420, 438 ]
144 silly gunzTarPerm extractEntry deps/msgpack/msgpack/fbuffer.hpp
145 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/fbuffer.hpp', 420, 438 ]
146 silly gunzTarPerm extractEntry deps/msgpack/msgpack/gcc_atomic.h
147 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/gcc_atomic.h', 420, 438 ]
148 silly gunzTarPerm extractEntry deps/msgpack/msgpack/iterator.hpp
149 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/iterator.hpp', 420, 438 ]
150 silly gunzTarPerm extractEntry deps/msgpack/msgpack/object.h
151 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/object.h', 420, 438 ]
152 silly gunzTarPerm extractEntry deps/msgpack/msgpack/object.hpp
153 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/object.hpp', 420, 438 ]
154 silly gunzTarPerm extractEntry deps/msgpack/msgpack/object_fwd.hpp
155 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/object_fwd.hpp', 420, 438 ]
156 silly gunzTarPerm extractEntry deps/msgpack/msgpack/pack.h
157 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/pack.h', 420, 438 ]
158 silly gunzTarPerm extractEntry deps/msgpack/msgpack/pack.hpp
159 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/pack.hpp', 420, 438 ]
160 silly gunzTarPerm extractEntry deps/msgpack/msgpack/pack_define.h
161 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/pack_define.h', 420, 438 ]
162 silly gunzTarPerm extractEntry deps/msgpack/msgpack/pack_template.h
163 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/pack_template.h', 420, 438 ]
164 silly gunzTarPerm extractEntry deps/msgpack/msgpack/sbuffer.h
165 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/sbuffer.h', 420, 438 ]
166 silly gunzTarPerm extractEntry deps/msgpack/msgpack/sbuffer.hpp
167 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/sbuffer.hpp', 420, 438 ]
168 silly gunzTarPerm extractEntry deps/msgpack/msgpack/cpp_config.hpp
169 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/cpp_config.hpp', 420, 438 ]
170 silly gunzTarPerm extractEntry deps/msgpack/msgpack/type.hpp
171 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/type.hpp', 420, 438 ]
172 silly gunzTarPerm extractEntry deps/msgpack/msgpack/unpack.h
173 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/unpack.h', 420, 438 ]
174 silly gunzTarPerm extractEntry deps/msgpack/msgpack/unpack.hpp
175 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/unpack.hpp', 420, 438 ]
176 silly gunzTarPerm extractEntry deps/msgpack/msgpack/unpack_define.h
177 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/unpack_define.h', 420, 438 ]
178 silly gunzTarPerm extractEntry deps/msgpack/msgpack/unpack_template.h
179 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/unpack_template.h', 420, 438 ]
180 silly gunzTarPerm extractEntry deps/msgpack/msgpack/util.h
181 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/util.h', 420, 438 ]
182 silly gunzTarPerm extractEntry deps/msgpack/msgpack/version.h
183 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/version.h', 420, 438 ]
184 silly gunzTarPerm extractEntry deps/msgpack/msgpack/version.hpp
185 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/version.hpp', 420, 438 ]
186 silly gunzTarPerm extractEntry deps/msgpack/msgpack/version_master.h
187 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/version_master.h', 420, 438 ]
188 silly gunzTarPerm extractEntry deps/msgpack/msgpack/versioning.hpp
189 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/versioning.hpp', 420, 438 ]
190 silly gunzTarPerm extractEntry deps/msgpack/msgpack/vrefbuffer.h
191 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/vrefbuffer.h', 420, 438 ]
192 silly gunzTarPerm extractEntry deps/msgpack/msgpack/vrefbuffer.hpp
193 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/vrefbuffer.hpp', 420, 438 ]
194 silly gunzTarPerm extractEntry deps/msgpack/msgpack/zbuffer.h
195 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/zbuffer.h', 420, 438 ]
196 silly gunzTarPerm extractEntry deps/msgpack/msgpack/zbuffer.hpp
197 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/zbuffer.hpp', 420, 438 ]
198 silly gunzTarPerm extractEntry deps/msgpack/msgpack/zone.h
199 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/zone.h', 420, 438 ]
200 silly gunzTarPerm extractEntry deps/msgpack/msgpack/zone.hpp
201 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack/zone.hpp', 420, 438 ]
202 silly gunzTarPerm extractEntry deps/msgpack/msgpack.gyp
203 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack.gyp', 420, 438 ]
204 silly gunzTarPerm extractEntry deps/msgpack/COPYING
205 silly gunzTarPerm modified mode [ 'deps/msgpack/COPYING', 420, 438 ]
206 silly gunzTarPerm extractEntry deps/msgpack/msgpack.hpp
207 silly gunzTarPerm modified mode [ 'deps/msgpack/msgpack.hpp', 420, 438 ]
208 silly gunzTarPerm extractEntry deps/msgpack/objectc.c
209 silly gunzTarPerm modified mode [ 'deps/msgpack/objectc.c', 420, 438 ]
210 silly gunzTarPerm extractEntry deps/msgpack/unpack.c
211 silly gunzTarPerm modified mode [ 'deps/msgpack/unpack.c', 420, 438 ]
212 silly gunzTarPerm extractEntry deps/msgpack/version.c
213 silly gunzTarPerm modified mode [ 'deps/msgpack/version.c', 420, 438 ]
214 silly gunzTarPerm extractEntry deps/msgpack/vrefbuffer.c
215 silly gunzTarPerm modified mode [ 'deps/msgpack/vrefbuffer.c', 420, 438 ]
216 silly gunzTarPerm extractEntry deps/msgpack/zone.c
217 silly gunzTarPerm modified mode [ 'deps/msgpack/zone.c', 420, 438 ]
218 silly gunzTarPerm extractEntry lib/msgpack.js
219 silly gunzTarPerm modified mode [ 'lib/msgpack.js', 420, 438 ]
220 silly gunzTarPerm extractEntry src/msgpack.cc
221 silly gunzTarPerm modified mode [ 'src/msgpack.cc', 420, 438 ]
222 silly gunzTarPerm extractEntry .travis.yml
223 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
224 silly gunzTarPerm extractEntry run_tests
225 silly gunzTarPerm modified mode [ 'run_tests', 493, 511 ]
226 silly gunzTarPerm extractEntry test/regression.js
227 silly gunzTarPerm modified mode [ 'test/regression.js', 420, 438 ]
228 silly gunzTarPerm extractEntry test/benchmark/benchmark.js
229 silly gunzTarPerm modified mode [ 'test/benchmark/benchmark.js', 420, 438 ]
230 silly gunzTarPerm extractEntry test/fixtures/stub.js
231 silly gunzTarPerm modified mode [ 'test/fixtures/stub.js', 420, 438 ]
232 silly gunzTarPerm extractEntry test/lib/msgpack.js
233 silly gunzTarPerm modified mode [ 'test/lib/msgpack.js', 420, 438 ]
234 verbose write writing to C:\Users\Petter\node_modules\msgpack\package.json
235 info preinstall msgpack@1.0.2
236 verbose readDependencies loading dependencies from C:\Users\Petter\node_modules\msgpack\package.json
237 verbose readDependencies loading dependencies from C:\Users\Petter\node_modules\msgpack\package.json
238 silly install resolved []
239 verbose about to build C:\Users\Petter\node_modules\msgpack
240 info build C:\Users\Petter\node_modules\msgpack
241 info linkStuff msgpack@1.0.2
242 silly linkStuff msgpack@1.0.2 has C:\Users\Petter\node_modules as its parent node_modules
243 verbose linkBins msgpack@1.0.2
244 verbose link bins [ { json2msgpack: './bin/json2msgpack',
244 verbose link bins     msgpack2json: './bin/msgpack2json' },
244 verbose link bins   'C:\Users\Petter\node_modules\.bin',
244 verbose link bins   false ]
245 verbose linkMans msgpack@1.0.2
246 verbose rebuildBundles msgpack@1.0.2
247 info install msgpack@1.0.2
248 verbose unsafe-perm in lifecycle true
249 info msgpack@1.0.2 Failed to exec install script
250 verbose unlock done using C:\Users\Petter\AppData\Roaming\npm-cache_locks\msgpack-68ee4676dba95d81.lock for C:\Users\Petter\node_modules\msgpack
251 verbose stack Error: msgpack@1.0.2 install: `node-gyp rebuild`
251 verbose stack Exit status 1
251 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
251 verbose stack     at emitTwo (events.js:87:13)
251 verbose stack     at EventEmitter.emit (events.js:172:7)
251 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
251 verbose stack     at emitTwo (events.js:87:13)
251 verbose stack     at ChildProcess.emit (events.js:172:7)
251 verbose stack     at maybeClose (internal/child_process.js:821:16)
251 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
252 verbose pkgid msgpack@1.0.2
253 verbose cwd C:\Users\Petter
254 error Windows_NT 10.0.10240
255 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "msgpack"
256 error node v4.2.6
257 error npm  v2.14.12
258 error code ELIFECYCLE
259 error msgpack@1.0.2 install: `node-gyp rebuild`
259 error Exit status 1
260 error Failed at the msgpack@1.0.2 install script 'node-gyp rebuild'.
260 error This is most likely a problem with the msgpack package,
260 error not with npm itself.
260 error Tell the author that this fails on your system:
260 error     node-gyp rebuild
260 error You can get their info via:
260 error     npm owner ls msgpack
260 error There is likely additional logging output above.
261 verbose exit [ 1, true ]
262 verbose unbuild node_modules\msgpack
263 info preuninstall msgpack@1.0.2
264 info uninstall msgpack@1.0.2
265 verbose unbuild rmStuff msgpack@1.0.2 from C:\Users\Petter\node_modules
266 silly gentlyRm C:\Users\Petter\node_modules.bin\json2msgpack.cmd is being gently removed
267 silly gentlyRm verifying C:\Users\Petter is an npm working directory
268 silly gentlyRm C:\Users\Petter\node_modules.bin\msgpack2json.cmd is being gently removed
269 silly gentlyRm verifying C:\Users\Petter is an npm working directory
270 silly gentlyRm containing path C:\Users\Petter is under npm's control, in C:\Users\Petter
271 silly gentlyRm deletion target C:\Users\Petter\node_modules.bin\json2msgpack.cmd is under C:\Users\Petter
272 verbose gentlyRm vacuuming from C:\Users\Petter\node_modules.bin\json2msgpack.cmd up to C:\Users\Petter
273 silly gentlyRm containing path C:\Users\Petter is under npm's control, in C:\Users\Petter
274 silly gentlyRm deletion target C:\Users\Petter\node_modules.bin\msgpack2json.cmd is under C:\Users\Petter
275 verbose gentlyRm vacuuming from C:\Users\Petter\node_modules.bin\msgpack2json.cmd up to C:\Users\Petter
276 silly vacuum-fs removing C:\Users\Petter\node_modules.bin\json2msgpack.cmd
277 silly vacuum-fs removing C:\Users\Petter\node_modules.bin\msgpack2json.cmd
278 silly vacuum-fs quitting because other entries in C:\Users\Petter\node_modules.bin
279 silly gentlyRm C:\Users\Petter\node_modules.bin\json2msgpack is being gently removed
280 silly gentlyRm verifying C:\Users\Petter is an npm working directory
281 silly gentlyRm containing path C:\Users\Petter is under npm's control, in C:\Users\Petter
282 silly gentlyRm deletion target C:\Users\Petter\node_modules.bin\json2msgpack is under C:\Users\Petter
283 verbose gentlyRm vacuuming from C:\Users\Petter\node_modules.bin\json2msgpack up to C:\Users\Petter
284 silly vacuum-fs quitting because other entries in C:\Users\Petter\node_modules.bin
285 silly gentlyRm C:\Users\Petter\node_modules.bin\msgpack2json is being gently removed
286 silly gentlyRm verifying C:\Users\Petter is an npm working directory
287 silly gentlyRm containing path C:\Users\Petter is under npm's control, in C:\Users\Petter
288 silly gentlyRm deletion target C:\Users\Petter\node_modules.bin\msgpack2json is under C:\Users\Petter
289 verbose gentlyRm vacuuming from C:\Users\Petter\node_modules.bin\msgpack2json up to C:\Users\Petter
290 silly vacuum-fs removing C:\Users\Petter\node_modules.bin\json2msgpack
291 silly vacuum-fs removing C:\Users\Petter\node_modules.bin\msgpack2json
292 silly vacuum-fs removing C:\Users\Petter\node_modules.bin
293 silly vacuum-fs removing C:\Users\Petter\node_modules.bin
294 silly vacuum-fs quitting because other entries in C:\Users\Petter\node_modules
295 silly vacuum-fs quitting because other entries in C:\Users\Petter\node_modules
296 info postuninstall msgpack@1.0.2
297 silly gentlyRm C:\Users\Petter\node_modules\msgpack is being purged from base C:\Users\Petter
298 verbose gentlyRm don't care about contents; nuking C:\Users\Petter\node_modules\msgpack
299 silly vacuum-fs purging C:\Users\Petter\node_modules\msgpack
300 silly vacuum-fs quitting because other entries in C:\Users\Petter\node_modules

**Comment by enochgroot** [comment]
Fixed in 2.0.0 (#25687, e04c9b55). Node 4 is outside `engines.node: ">=18"`.

**Comment by enochgroot** [comment]
Re-evaluated on master `e04c9b55`. `engines.node` is `>=18`; CI is Node 18/20/22. Node 4 is unsupported. Closing as obsolete.
